//>>built
require({cache:{"bkp/MobilePictureViewer":function(){define("bkp/MobilePictureViewer",["dojo/query","dojo/dom-style","dojo/dom","dojo/_base/array","dojo/dom-construct","dojo/_base/window","dojo/io/script","dojo/_base/connect","dojo/dom-attr","dojox/mobile/parser","dojox/mobile","dojox/mobile/SwapView","dojox/mobile/ScrollableView","dojox/mobile/ListItem","dojox/mobile/Heading","dojox/mobile/RoundRectList"],function(n,s,y,j,e,k,t,o,u,C,D,z,v,A,p,B){return function(){var c,w=!1,x=[],f=[],q=-1,g,r=!1,
l,h=0,m=0,m=h=0;return c={reorient:function(){window.scrollTo(0,1);window.orientation!=0?(h=window.screen.availHeight,m=window.screen.availWidth-95):(h=window.screen.availWidth,m=window.screen.availHeight-75);n(".flippableImage").forEach(function(a){s.set(a,"max-width",h+"px");s.set(a,"max-height",m+"px")})},clearWidgets:function(){j.forEach(dijit.registry.toArray(),function(a){a.destroy()})},createAlbumLinks:function(){var a=y.byId("albumList");j.forEach(f,function(d,b){if(f[b].match(BKPConstants.kidName)){var i=
"album"+b;e.create("li",{id:i,innerHTML:f[b]},a);(new A({href:"#",onClick:function(){c.clearWidgets();c.loadAlbumThumbnails(b)},transition:"slide"},i)).startup()}});e.create("div",{style:"text-align:center;",innerHTML:"<a href=pictures.html>Classic View</a>"},a,"after")},populateAlbums:function(){e.create("div",{id:"albums",innerHTML:"<h1 id=albumsHeader fixed=top>"+BKPConstants.kidNames+" Pictures</h1><ul id=albumList>"},k.body());var a=new v({selected:!0},"albums"),d=new p({},"albumsHeader"),b=
new B({},"albumList");w?(c.createAlbumLinks(),a.startup(),d.startup(),b.startup()):t.get({url:"http://picasaweb.google.com/data/feed/api/user/"+BKPConstants.picasaUserName+"?kind=album&access=visible&alt=json",callbackParamName:"callback",load:function(e){j.forEach(e.feed.entry,function(a,c){f[c]=a.media$group.media$title.$t;if(f[c].match(BKPConstants.kidName)){f[c].match("Bump")&&(f[c]=BKPConstants.kidName+" Baby Bump Pictures");var b="http://picasaweb.google.com/data/feed/api/user/"+BKPConstants.picasaUserName+
"/albumid/";b+=a.gphoto$id.$t;b+="?alt=json&thumbsize=48&imgmax=1024";x[c]=b}});w=!0;c.createAlbumLinks();a.startup();d.startup();b.startup()}})},createThumbnailLinks:function(a){for(thumbnailIndex in g)e.create("img",{albumIndex:a,thumbnailIndex:thumbnailIndex,"class":"thumbnail",src:g[thumbnailIndex]},"thumbnails")},loadAlbumThumbnails:function(a){q!=a&&(r=!1);q=a;var d="<h1 id=thumbnailsHeader fixed=top>";d+=f[a];d+="</h1><div id=thumbnails></div>";var d=e.create("div",{id:"thumbnailsView",innerHTML:d},
k.body()),b=o.connect(d,"onclick",null,function(a){var b=a.target;if(b.parentNode!==k.body()){var d=Number(u.get(b,"albumIndex")),b=Number(u.get(b,"thumbnailIndex"));c.clearWidgets();c.loadAlbum(d,b)}a.preventDefault()}),i=new v({selected:!0},"thumbnailsView"),h=new p({back:"Albums",onClick:function(){o.disconnect(b);c.clearWidgets();c.populateAlbums()}},"thumbnailsHeader");r?(c.createThumbnailLinks(a),i.startup(),h.startup()):t.get({url:x[a],callbackParamName:"callback",load:function(b){g=[];l=[];
j.forEach(b.feed.entry,function(a,b){g[b]=a.media$group.media$thumbnail[0].url;l[b]=a.media$group.media$content[0].url});r=!0;c.createThumbnailLinks(a);i.startup();h.startup()}})},createPhotoViews:function(a,d){for(urlIndex in l){var b="image"+urlIndex,i="photoHeader"+urlIndex,j=e.create("div",{id:b},k.body()),g=e.create("div",{"class":"imageView"},j);e.create("h1",{id:i},g);g=e.create("a",{href:l[urlIndex],target:"_blank"},g);e.create("img",{"class":"flippableImage",style:"max-width:"+h+"px;max-height:"+
m+"px;",src:l[urlIndex]},g);e.place(j,k.body());b=new z({selected:urlIndex==d},b);b.startup();urlIndex==d&&b.show();new p({back:f[a],onClick:function(){c.clearWidgets();c.loadAlbumThumbnails(q)}},i)}},loadAlbum:function(a,d){c.createPhotoViews(a,d)},connectReorientFcn:function(){window.onorientationchange!==void 0&&o.connect(dojo.global,"onorientationchange",function(){c.reorient()})}}}()})}}});require(["dojo/i18n"],function(n){n._preloadLocalizations("bkp/layers/nls/mobilepictures",[])});
define("bkp/layers/mobilepictures",[],1);